version: '3'

services:
  mappy:
    container_name: mappy
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    restart: always
    ports:
      - 3000:3000