version: '3.9'

services:
  mappy:
    container_name: mappy
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
#         ENV_VARIABLE: ${ENV_VARIABLE}
#         NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
        restart: always
        ports:
          3000:3000