version: '3'

services:
  mappy:
    container_name: mappy
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/app
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
